version: '3'
services:
 postgres:
  image: postgres:13.3
  environment:
    POSTGRES_DB: "database"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "admin_postgres"
  ports:
    - "5432:5432"
volumes:
  postgres: